<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit466c0561d503d08fa9c73013fcb539cb
{
    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit466c0561d503d08fa9c73013fcb539cb::$classMap;

        }, null, ClassLoader::class);
    }
}
