<?php
/**
 * Storage Service class.
 *
 * Handles filesystem operations for test scripts.
 * Manages the dual-write pattern where scripts are saved to both
 * database and filesystem for direct browser access.
 *
 * @package TestScriptManager
 */

namespace TSM\Services;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Storage Service class.
 *
 * Provides filesystem operations for test scripts:
 * - Write script files to {ABSPATH}/test-scripts/
 * - Read script content from filesystem
 * - Delete script files
 * - Generate browser-accessible URLs
 *
 * Each script file includes a header that loads wp-load.php,
 * making them directly executable via browser.
 */
class StorageService {

	/**
	 * Directory name for test scripts.
	 */
	const SCRIPTS_DIR = 'test-scripts';

	/**
	 * File prefix for script files.
	 */
	const FILE_PREFIX = 'test-';

	/**
	 * File extension for script files.
	 */
	const FILE_EXTENSION = '.php';

	/**
	 * Header template for script files.
	 * Includes wp-load.php for WordPress environment access.
	 */
	const FILE_HEADER = "<?php\n// Auto-generated by Test Script Manager\n// Slug: %s\n// WARNING: Do not edit directly - changes will be overwritten\nrequire_once __DIR__ . '/../wp-load.php';\n\n";

	/**
	 * Write script code to filesystem.
	 *
	 * Creates a PHP file in the scripts directory with a header
	 * that loads WordPress environment.
	 *
	 * @param string $slug Script slug (used as filename).
	 * @param string $code Script code content.
	 * @return true|\WP_Error True on success, WP_Error on failure.
	 */
	public static function write_to_filesystem( $slug, $code ) {
		// Ensure directory exists.
		$dir_result = self::ensure_directory_exists();
		if ( is_wp_error( $dir_result ) ) {
			return $dir_result;
		}

		$file_path = self::get_script_path( $slug );

		// Build file content with header.
		$header  = sprintf( self::FILE_HEADER, $slug );
		$content = $header . $code;

		// Write file using WordPress filesystem functions.
		global $wp_filesystem;

		// Initialize WP_Filesystem if not already done.
		if ( ! function_exists( 'WP_Filesystem' ) ) {
			require_once ABSPATH . 'wp-admin/includes/file.php';
		}
		WP_Filesystem();

		// Attempt to write file.
		$result = $wp_filesystem->put_contents( $file_path, $content, FS_CHMOD_FILE );

		if ( false === $result ) {
			return new \WP_Error(
				'tsm_file_write_failed',
				sprintf(
					/* translators: %s: File path */
					__( 'Failed to write script file: %s', 'test-script-manager' ),
					$file_path
				)
			);
		}

		return true;
	}

	/**
	 * Read script code from filesystem.
	 *
	 * Reads the script file and removes the auto-generated header,
	 * returning only the user's code.
	 *
	 * @param string $slug Script slug.
	 * @return string|\WP_Error Script code on success, WP_Error on failure.
	 */
	public static function read_from_filesystem( $slug ) {
		$file_path = self::get_script_path( $slug );

		if ( ! file_exists( $file_path ) ) {
			return new \WP_Error(
				'tsm_file_not_found',
				sprintf(
					/* translators: %s: Script slug */
					__( 'Script file not found: %s', 'test-script-manager' ),
					$slug
				)
			);
		}

		// Read file content.
		$content = file_get_contents( $file_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents

		if ( false === $content ) {
			return new \WP_Error(
				'tsm_file_read_failed',
				sprintf(
					/* translators: %s: Script slug */
					__( 'Failed to read script file: %s', 'test-script-manager' ),
					$slug
				)
			);
		}

		// Remove the auto-generated header.
		// Find the position after the header (double newline after require_once).
		$header_pattern = '/^<\?php\n\/\/ Auto-generated by Test Script Manager\n\/\/ Slug: [a-z0-9-]+\n\/\/ WARNING: Do not edit directly - changes will be overwritten\nrequire_once __DIR__ \. \'\/\.\.\/wp-load\.php\';\n\n/';

		$code = preg_replace( $header_pattern, '', $content );

		return $code;
	}

	/**
	 * Delete script file from filesystem.
	 *
	 * @param string $slug Script slug.
	 * @return true|\WP_Error True on success, WP_Error on failure.
	 */
	public static function delete_from_filesystem( $slug ) {
		$file_path = self::get_script_path( $slug );

		// File doesn't exist - consider it success.
		if ( ! file_exists( $file_path ) ) {
			return true;
		}

		// Delete the file.
		$result = wp_delete_file( $file_path );

		// Check if file still exists after deletion attempt.
		if ( file_exists( $file_path ) ) {
			return new \WP_Error(
				'tsm_file_delete_failed',
				sprintf(
					/* translators: %s: Script slug */
					__( 'Failed to delete script file: %s', 'test-script-manager' ),
					$slug
				)
			);
		}

		return true;
	}

	/**
	 * Get the browser-accessible URL for a script.
	 *
	 * @param string $slug Script slug.
	 * @return string Script URL.
	 */
	public static function get_script_url( $slug ) {
		$filename = self::FILE_PREFIX . $slug . self::FILE_EXTENSION;
		return home_url( self::SCRIPTS_DIR . '/' . $filename );
	}

	/**
	 * Get the filesystem path for a script.
	 *
	 * @param string $slug Script slug.
	 * @return string Full filesystem path.
	 */
	public static function get_script_path( $slug ) {
		$filename = self::FILE_PREFIX . $slug . self::FILE_EXTENSION;
		return self::get_scripts_directory() . '/' . $filename;
	}

	/**
	 * Get the scripts directory path.
	 *
	 * @return string Scripts directory path.
	 */
	public static function get_scripts_directory() {
		return ABSPATH . self::SCRIPTS_DIR;
	}

	/**
	 * Ensure the scripts directory exists and is writable.
	 *
	 * Creates the directory if it doesn't exist with appropriate permissions.
	 *
	 * @return true|\WP_Error True on success, WP_Error on failure.
	 */
	private static function ensure_directory_exists() {
		$dir_path = self::get_scripts_directory();

		// Directory already exists.
		if ( is_dir( $dir_path ) ) {
			if ( ! is_writable( $dir_path ) ) {
				return new \WP_Error(
					'tsm_directory_not_writable',
					sprintf(
						/* translators: %s: Directory path */
						__( 'Scripts directory is not writable: %s', 'test-script-manager' ),
						$dir_path
					)
				);
			}
			return true;
		}

		// Create directory with appropriate permissions.
		$result = wp_mkdir_p( $dir_path );

		if ( false === $result ) {
			return new \WP_Error(
				'tsm_directory_create_failed',
				sprintf(
					/* translators: %s: Directory path */
					__( 'Failed to create scripts directory: %s', 'test-script-manager' ),
					$dir_path
				)
			);
		}

		// Set permissions (0755 for directory).
		chmod( $dir_path, 0755 ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_chmod

		// Create .htaccess to protect directory listing but allow PHP execution.
		$htaccess_path    = $dir_path . '/.htaccess';
		$htaccess_content = "# Test Script Manager - Generated automatically\n# Allow PHP execution but prevent directory listing\nOptions -Indexes\n";

		file_put_contents( $htaccess_path, $htaccess_content ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents

		// Create index.php for additional security.
		$index_path    = $dir_path . '/index.php';
		$index_content = "<?php\n// Silence is golden.\n";

		file_put_contents( $index_path, $index_content ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents

		return true;
	}

	/**
	 * Check if a script file exists.
	 *
	 * @param string $slug Script slug.
	 * @return bool True if file exists.
	 */
	public static function file_exists( $slug ) {
		return file_exists( self::get_script_path( $slug ) );
	}
}
